name: CI
on:
  release:
    types: [ published ]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up java version
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Build Maven project
        run: |
          if [ -n "${{ github.event.release.tag_name }}" ]; then
            mvn --batch-mode package -Dreststop.version="${{ github.event.release.tag_name }}"
          else
            mvn --batch-mode package
          fi
      - name: Publish package
        if: github.event_name == 'release'
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
